name: ru_psu_timetable
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  icalendar_parser: ^2.0.0
  google_fonts: ^6.3.2

  cupertino_icons: ^1.0.8
  animated_theme_switcher: ^2.0.10
  sidebarx: ^0.17.2
  lottie: ^3.3.2
  connectivity_plus: ^5.0.1
  share_plus: ^9.0.0
  path_provider: ^2.1.3
  intl: ^0.20.2
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.0.0
  flutter_launcher_icons: ^0.14.4
  dynamic_color: ^1.7.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter




  http: ^1.1.0
  icalendar_parser: ^2.0.0

  cupertino_icons: ^1.0.8
  animated_theme_switcher: ^2.0.10
  sidebarx: ^0.17.2
  lottie: ^3.3.2
  connectivity_plus: ^5.0.1
  share_plus: ^9.0.0
  path_provider: ^2.1.3
  intl: ^0.20.2
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.0.0
  dynamic_color: ^1.7.0

  flutter_localizations:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/


  uses-material-design: true



